#!/bin/bash

# (C) Rick van Helvert
# Quick music control system relying on playerctl; this means it can control any player playerctl can handle! :D


command="$1"
man_player="$2"
getplayer() {
    if [ "$man_player" == 0 ]; then
        cmd="$(playerctl status -a --format '{{ playerName }}:{{ status }}' | grep Playing)"
        player="$(echo $cmd | cut -d ":" -f 1)"
    else
        player="$man_player"
    fi
}
commandplayer() {
    getplayer
    if [ "$command" == "next" ]; then
        playerctl -p "$player" next
    elif [ "$command" == "prev" ]; then
        playerctl -p "$player" previous
    elif [ "$command" == "toggle" ]; then
        playerctl -p "$player" play-pause
    fi
}
commandplayer
